### ISSUE TITLE
CMake build issues with GCC

### ISSUE THREAD

**Issue by 3e33** [OpenMathLib/OpenBLAS#5927]
I'm building from source on Ubuntu with GCC (from `apt install build-essential`) and CMake, the compilation runs fine, these are my build flags:
```
cmake -S . -B build -G "Ninja" \
 -DDYNAMIC_ARCH=OFF \
 -DBUILD_SHARED_LIBS=OFF \
 -DCMAKE_BUILD_TYPE=Release \
 -DBUILD_TESTING=OFF \
 -DBUILD_STATIC_LIBS=ON \
 -DNOFORTRAN=ON \
 -DTARGET=NEHALEM
```

Everything compiles fine, until I try to use it with:
```
find_package(BLAS REQUIRED)
find_package(LAPACK REQUIRED)
```

In version `OpenBLAS-0.3.21` find BLAS works, but find LAPACK fails its `/usr/bin/cc -DCHECK_FUNCTION_EXISTS=cheev_ -g` check with error:
```
OpenBLAS/lib/libopenblas.a(cheev.c.o): in function `cheev_':
cheev.c:(.text+0x50b): undefined reference to `sqrtf'
```

In version `OpenBLAS-0.3.34`, find BLAS also fails, with similar errors.

I get no errors during compilation, only when CMake's `find_package` does its function check. I have compiled and used OpenBLAS successfully in the past but I used Clang as the compiler, this time I'm using GCC 11.4 and I can't seem to get it to work.

What's strange to me is that `find_package(BLAS)` works on 0.3.21 and doesn't on 0.3.34.

**Comment by martin-frbg** [comment]
That's an implicit dependency on the standard math library (libm), and apparently CMake's find script doesn't set `CMAKE_REQUIRED_LIBRARY=-lm` when searching for OpenBLAS. You could try if adding `EXTRALIB=-lm` to the build options for OpenBLAS works around this

**Comment by 3e33** [comment]
@martin-frbg I actually already tried that, and the find script became:
`/usr/bin/cc -DCHECK_FUNCTION_EXISTS=cheev_ -g -lm`

But it made no difference.

**Comment by martin-frbg** [comment]
Hmm, the toplevel CMakeLists.txt already sets target_link_libraries to add libm, not sure what's going wrong here. (That line - with an older comment about Android needing libm - was added in 0.3.22 as PR #3895 but I get a github internal error when I try to open that PR to recall the context)

**Comment by 3e33** [comment]
@martin-frbg I found a solution:
The problem is doing `set(CMAKE_REQUIRED_LINK_OPTIONS "-lm")` doesn't work because it puts the `-lm` too early in the commandline, the flag isn't used. But you can do `set(CMAKE_REQUIRED_LINK_OPTIONS "-Wl,--no-as-needed;-lm")`, then `find_package` does the linking properly.

**Comment by martin-frbg** [comment]
It isn't clear to me yet if this is something OpenBLAS is doing wrong, or could be doing better. I cannot even seem to find anybody else who encountered this problem in the past

**Comment by 3e33** [comment]
@martin-frbg Turns out I was wrong, I'm getting the same issue even with Clang as the compiler.
```
/usr/bin/clang -DCHECK_FUNCTION_EXISTS=cheev_ -g  CMakeFiles/cmTC_fab0f.dir/Debug/CheckFunctionExists.c.o -o Debug/cmTC_fab0f  /home/OpenBLAS/lib/libopenblas.a
```

Exact same solution as well.
```
set(CMAKE_REQUIRED_LINK_OPTIONS "-Wl,--no-as-needed;-lm")
find_package(BLAS REQUIRED)
find_package(LAPACK REQUIRED)
unset(CMAKE_REQUIRED_LINK_OPTIONS)
```

Maybe this is a CMake issue.

**Comment by martin-frbg** [comment]
I don't see us doing anything differently than Reference-LAPACK in the build, but OpenBLAS is more likely to have (grown) a reference to (libm) sqrt somewhere on the call graph of cheev. So if the author of that particular find_package cunningly chose CHEEV as a LAPACK function that would be self-contained in any implementation, some change especially in the level2/level3 multithreading setup may have foiled the plan. Maybe the CMAKE_REQUIRED_LINK_OPTIONS needs to be documented somewhere to save others the trouble.
